### ISSUE TITLE
is bygpay a new payment system? 

### ISSUE THREAD

**Issue by aberba** [nukturnal/bygpay_dotnet#1]
Just curious. I wrote an MPower D api to publish only to realize the platform just died. If bygpay is one I could prob write an api in D.

**Comment by nukturnal** [comment]
Bygpay is very different from MPower and not publicly available for testing. The .NET library is not even ready but you can checkout the Fully functional [Ruby SDK](https://github.com/nukturnal/bygpay_ruby). That should give u an idea of whats going into it.

**Comment by aberba** [comment]
Ha ha. I really not a fun of ruby but I get it. The routes are handled on the server and quests are sent there. Since the response seem like JSON, it shouldn't be much problem when its completed (or is the SDK complete?)

outside question, how do you guys tap into the telco apis and banks to make transaction, my guess... a proprietary black box :)
